config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :users, :photos, :sessions
  get '/admin',        to: 'sessions#new'
  get '/about',        to: 'main#about'
  get '/testimonials', to: 'main#testimonials'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
  helper_method :current_user
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photo = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)

    if @photo.save
      flash[:notice] = "Photo saved successfully!"
      redirect_to @photo
    else
      flash[:error] = "Photo not saved!"
      render :new
    end
  end

  def show 
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:file, :category, :homepage)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Logged In!"
      redirect_to @user
    else
      flash[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user  = User.find(params[:id])
    @photo = Photo.new 
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <p class='alert alert-danger center'><%=h flash[:error] %></p>
<% end %>
<% if flash[:notice] %>
  <p class='alert alert-success center'><%=h flash[:notice] %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
   <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

  <title><%= content_for?(:title) ? yield(:title) : "Christian Construction" %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
 <body>
  <div class="navbar navbar-default navbar-cc navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to do %>
          <%= image_tag 'logo.png', style: "width:300px;", :class => "cc-logo" %>
        <% end %>

      </div>
      <div class="collapse navbar-collapse">

        <ul class="nav navbar-nav pull-right">
          <li >
            <%= link_to "About", about_path %>
          </li>
          <li >
            <%= link_to "Portfolio", "" %>
          </li>
          <li >
            <%= link_to "Testimonials", testimonials_path %>
          </li>
          <li >
            <%= link_to "Contact", "" %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <div class="container container-main">
  <%= render 'layouts/flash' %>
  <%= yield %>
  </div><!-- /.container -->
</body>
</html>

app/views/main/_carousel.html.erb
<div id="carousel-homepage" class="carousel slide carousel-homepage" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-homepage" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-homepage" data-slide-to="1"></li>
    <li data-target="#carousel-homepage" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
        <%= image_tag "latchfords.jpg" %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-homepage" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-homepage" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/main/about.html.erb
<div class="main-page-wrapper">
  <div class="row text-center main-header">
    <h1>
      About Us
    </h1>
  </div>

  <div class="about-wrapper">
    <p>
      Since 1990, Wayne Christian, with Christian Construction has helped Bay Area homeowners make their remodeling dreams a reality. Our experienced craftsmen and personal attention to each project ensures that every customer is 100% satisfied. As the owner, I personally oversee every job from start to finish.
    <p>

    <h3>
      Wayne Christian's Experience
    </h3>

    <p>
      Wayne Christian graduated from California Polytechnic State University, San Luis Obispo, with a degree in Construction Management from the School of Architecture. He first started working as a Project Engineer on the 26 story Hilton Hotel in San Francisco. After working as a Construction Coordinator, building Custom Homes in Blackhawk, he decided to start his own construction company specializing in the design and remodeling of kitchens and bathrooms. Christian Construction has been a licensed General Contract and in business for 22 years.
    </p>

    <h3>
      Why Christian Construction?
    </h3>

    <p>
      We listen to our clients. We make note of all of the things that are important to you no matter how small the detail. We've heard many times from our past homeowners that it was the small things we did that made the job go so smoothly. We will do everything we can to gain your confidence, so you can sit back and enjoy watching your dream come true.
    </p>

    <h3>
      Talk To Our Past Homeowners
    </h3>

    <p>
      Please check out our Yelp reviews showing our many 5 star testimonials of past homeowners that have nothing but great things to say about us! Our goal for every job is to have the homeowner call us back for repeat business.
    </p>

    <h3>
      We Want To Be Your Contractor For Life
    </h3>

    <p>
      We are very proud of our long list of repeat and referral homeowners. 95% of our homeowners call us back with-in the first two years to do another bathroom, kitchen, or a home project. We have been serving some of our homeowners for over 20 years. We always give "the family discount" to our past homeowners, as well as a lifetime of free cabinet tune-ups and adjustments.
    </p>
    
  </div>
</div>

app/views/main/index.html.erb
<!-- <div class='main-side-menu'>
  <%= image_tag 'kitchens.png'  %>
  <%= image_tag 'bathrooms.png' %>
  <%= image_tag 'remodels.png'  %>
  <%= image_tag 'testimonials.png' %>
  <%= image_tag 'yelp.png' %>
  <%= image_tag 'facebook.png' %>
  <%= image_tag 'google.png' %>
</div> -->

<%= render 'main/carousel' %>

app/views/photos/new.html.erb
<div class="photo-upload-form-wrapper">
  <div class="center">
    <h2>
      Photo Upload:    
    </h2>
  </div>
  <div class="photo-upload-form">
    <%= form_for @photo do |f| %>
      <div class="photo-form-input">
        <%= f.file_field :file, :class=>"form-input" %>
      </div>
      <div class="photo-form-input">
        <%= f.select :category, options_for_select([
            ['Kitchens','kitchens'],
            ['Baths'   ,'baths'],
            ['Remodels','remodels']
            ]), :class=>"form-input" %>
      </div>
      <div class="photo-form-input">
        <%= f.check_box :homepage, :class => "checkbox inline pull-left" %>
        <%= f.label "homepage?", :class => "pull-left" %>
      </div>
  </div>
  <div class="center photo-upload-submit">
    <%= f.submit "Upload Photo!", :class => "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/photos/show.html.erb
<div class="photo-show-wrapper">
  <div class="center">
    <%= image_tag @photo.file_url.to_s %>
  </div>
</div>

app/views/users/new.html.erb
<div class="user-form">
  <%= form_for @user do |f| %>
  <%= f.text_field :email, :class => "form-control", placeholder: :email %>
  <%= f.password_field :password, :class => "form-control", placeholder: :password %>
  <div class="center">
    <%= f.submit "Sign Up", :class => "btn btn-primary" %>
  </div>
  <% end %>
</div>